---
- name: Set hostname
  hostname:
    name: "{{ server_hostname }}.{{ dhcp_global_domain_name }}"
    use: systemd
  when: server_hostname

- name: Remove items
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_items: ["{{ remove_items }}"]

- name: Add dirs
  ansible.builtin.file:
    state: directory
    path: "{{ item.dir }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    recurse: "{{ item.recurse | default(true) }}"
    mode: "{{ item.mode | default(true) }}"
  with_items: ["{{ gen_dirs }}"]

- name: Do OS updates
  ansible.builtin.include_tasks: distribution-update.yaml
  when: do_dist_update

- name: Remove Packages
  ansible.builtin.dnf:
    name: "{{ remove_packages }}"
    state: removed

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: do_update

- name: Install Packages
  ansible.builtin.dnf:
    name: "{{ install_packages + mandatory_packages }}"
    state: present

- name: Set SELinux to permissive
  selinux:
    state: "{{ selinux_state }}"
    policy: targeted

- name: Start SVCs
  ansible.builtin.systemd_service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled | default(true) }}"
    state: "{{ item.state | default('restarted') }}"
    daemon_reload: "{{ item.reload | default(false) }}"
  with_items: ["{{ services }}"]

- name: Do sensors
  ansible.builtin.shell: yes | sensors-detect > /tmp/sensors_detected
  args:
    creates: /tmp/sensors_detected

- name: Configure power behavior
  template:
    dest: /etc/systemd/logind.conf
    src: logind.conf.j2

- name: Set TZ
  timezone:
    name: "{{ timezone }}"
    hwclock: UTC

- name: Configure access
  ansible.builtin.include_tasks: access.yaml

- name: Disable firewalld
  include_tasks: disable_firewalld.yaml
  when: do_disable_firewalld

- name: Setup kitty
  block:
    - name: Add dir
      ansible.builtin.file:
        state: directory
        path: "{{ ansible_user_dir }}/.terminfo/"
    - name: Copy the terminfo
      ansible.builtin.copy:
        src: kitty/kitty.terminfo
        dest: "{{ ansible_user_dir }}/.terminfo/kitty.terminfo"
